import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";

const root = process.cwd();
const skillPath = path.join(root, "skills", "forgeloop", "SKILL.md");
const generator = path.join(root, "scripts", "generate-forgeloop-skill.mjs");

test("generated skill has portable frontmatter and required safety sections", async () => {
  const content = await readFile(skillPath, "utf8");
  assert.match(content, /^---\nname: forgeloop\ndescription: [\s\S]+?\n---\n/u);
  for (const heading of ["Purpose", "When to Use", "Source of Truth", "Command Resolution", "Operating Workflow", "Verification Rules", "Recovery Rules", "Completion Rule", "Cross-Harness Continuity", "Never Do", "References"]) {
    assert.match(content, new RegExp(`^## ${heading}$`, "m"));
  }
  assert.match(content, /Generated by scripts\/generate-forgeloop-skill\.mjs/u);
  assert.match(content, /complete.*VALID/u);
  assert.match(content, /record-check.*never.*executed/u);
  assert.doesNotMatch(content, /npm install -g forgeloop|npx skills add|curl .*\| sh/u);
  assert.ok((await stat(skillPath)).size <= 16 * 1024);
});

test("skill generation is deterministic and fresh", () => {
  execFileSync(process.execPath, [generator, "--check"], { cwd: root, stdio: "pipe" });
  execFileSync(process.execPath, [generator, "--write"], { cwd: root, stdio: "pipe" });
  execFileSync(process.execPath, [generator, "--check"], { cwd: root, stdio: "pipe" });
});

test("generated references resolve and remain bounded", async () => {
  const skill = await readFile(skillPath, "utf8");
  for (const reference of ["lifecycle.md", "verification.md", "recovery.md"]) {
    const referencePath = path.join(root, "skills", "forgeloop", "references", reference);
    assert.ok((await stat(referencePath)).isFile());
    assert.ok((await stat(referencePath)).size <= 16 * 1024);
    assert.match(skill, new RegExp(`references/${reference.replace(".", "\\.")}`, "u"));
  }
});
