import assert from "node:assert/strict";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";

import { COMMANDS } from "../src/cli.js";
import { ARTIFACT_REGISTRY } from "../src/core/artifact-registry.js";
import { CLI_COMMAND_METADATA } from "../src/core/cli-metadata.js";
import { ALL_KNOWN_ERROR_CODES, PUBLIC_ERROR_CODES } from "../src/core/error-codes.js";
import { readSchema } from "../src/core/schema-validation.js";
import { getPackageRoot } from "../src/core/templates.js";
import { validateDocumentationConformance } from "../scripts/validate_documentation_conformance.mjs";

const packageRoot = getPackageRoot();

test("validateDocumentationConformance passes on repository docs", async () => {
  const result = await validateDocumentationConformance();
  assert.equal(result.valid, true, `Expected valid documentation conformance, got errors: ${result.errors.join("\n")}`);
  assert.equal(result.errors.length, 0);
  assert.ok(result.summary.taggedArtifactsCount >= 12);
  assert.equal(result.summary.commandsCount, 27);
  assert.ok(result.summary.publicErrorCodesCount >= 13);
  assert.equal(result.summary.discoverySurfacesCount, 4);
});

test("ARTIFACT_REGISTRY covers all public schemas and matches ARTIFACT_REFERENCE", async () => {
  for (const [key, artifact] of Object.entries(ARTIFACT_REGISTRY)) {
    assert.ok(artifact.key, `Artifact ${key} must have key`);
    assert.ok(artifact.path, `Artifact ${key} must have path`);
    assert.ok(artifact.schema, `Artifact ${key} must have schema`);
    assert.ok(artifact.owner, `Artifact ${key} must have owner`);
    assert.ok(artifact.mutability, `Artifact ${key} must have mutability`);
    assert.ok(artifact.trustRole, `Artifact ${key} must have trustRole`);

    // Verify schema can be loaded
    const schema = await readSchema(artifact.schema, packageRoot);
    assert.ok(schema, `Schema ${artifact.schema} must load successfully`);
  }
});

test("CLI_COMMAND_METADATA covers all 27 commands with valid options and mutation flags", () => {
  assert.equal(Object.keys(CLI_COMMAND_METADATA).length, 27);
  for (const command of COMMANDS) {
    const meta = CLI_COMMAND_METADATA[command];
    assert.ok(meta, `Command ${command} must exist in CLI_COMMAND_METADATA`);
    assert.equal(meta.name, command);
    assert.ok(["lifecycle", "continuity", "verification", "policy-audit", "project-maintenance", "diagnostics"].includes(meta.category));
    assert.ok(["READ_ONLY", "MUTATING", "EXTERNAL_EXECUTION"].includes(meta.mutation));
    assert.ok(Array.isArray(meta.options));
    assert.ok(meta.options.includes("--help"));
    assert.ok(meta.options.includes("--version"));
  }
});

test("PUBLIC_ERROR_CODES covers all documented stable codes", () => {
  for (const [key, errorMeta] of Object.entries(PUBLIC_ERROR_CODES)) {
    assert.equal(key, errorMeta.code);
    assert.equal(errorMeta.classification, "PUBLIC_STABLE");
    assert.ok(errorMeta.meaning);
    assert.ok(errorMeta.safeResolution);
    assert.ok(ALL_KNOWN_ERROR_CODES.has(errorMeta.code));
  }
});

test("negative fixtures: validateDocumentationConformance detects doc drift", async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "forgeloop-doc-test-"));

  try {
    // Copy repository structure to tempDir
    await cp("docs", path.join(tempDir, "docs"), { recursive: true });
    await cp("schemas", path.join(tempDir, "schemas"), { recursive: true });
    await cp("src", path.join(tempDir, "src"), { recursive: true });
    await cp("AGENTS.md", path.join(tempDir, "AGENTS.md"));
    await cp("CLAUDE.md", path.join(tempDir, "CLAUDE.md"));
    await cp(".cursor", path.join(tempDir, ".cursor"), { recursive: true });
    await cp(".github", path.join(tempDir, ".github"), { recursive: true });

    // Baseline check
    const baseline = await validateDocumentationConformance({ rootDir: tempDir });
    assert.equal(baseline.valid, true);

    // Negative Case 1: Extra fake property in ARTIFACT_REFERENCE
    const docFile = path.join(tempDir, "docs", "ARTIFACT_REFERENCE.md");
    let content = await readFile(docFile, "utf8");
    const corruptedContent1 = content.replace(
      "- `taskId` *(string, required)*",
      "- `taskId` *(string, required)*\n- `fakeProperty` *(string, optional)*",
    );
    await writeFile(docFile, corruptedContent1, "utf8");
    const test1 = await validateDocumentationConformance({ rootDir: tempDir });
    assert.equal(test1.valid, false);
    assert.ok(test1.errors.some((e) => e.includes("DOC_SCHEMA_FIELD_EXTRA") && e.includes("fakeProperty")));

    // Negative Case 2: Claiming stdout/stderr log persistence in execution artifact
    const corruptedContent2 = content.replace(
      "Attested command execution provenance artifact generated by `forgeloop run-check`.",
      "Execution artifact that captures output logs and stdout/stderr logs.",
    );
    await writeFile(docFile, corruptedContent2, "utf8");
    const test2 = await validateDocumentationConformance({ rootDir: tempDir });
    assert.equal(test2.valid, false);
    assert.ok(test2.errors.some((e) => e.includes("DOC_EXECUTION_STDOUT_CLAIM")));

    // Restore artifact reference
    await writeFile(docFile, content, "utf8");

    // Negative Case 3: Fake CLI command documented
    const cliDocFile = path.join(tempDir, "docs", "CLI_REFERENCE.md");
    let cliContent = await readFile(cliDocFile, "utf8");
    await writeFile(cliDocFile, `${cliContent}\n\n### \`fake-command\`\n\nA fake command.\n`, "utf8");
    const test3 = await validateDocumentationConformance({ rootDir: tempDir });
    assert.equal(test3.valid, false);
    assert.ok(test3.errors.some((e) => e.includes("DOC_CLI_COMMAND_EXTRA") && e.includes("fake-command")));

    // Restore CLI reference
    await writeFile(cliDocFile, cliContent, "utf8");

    // Negative Case 4: Missing adapter resume rule
    const agentsFile = path.join(tempDir, "AGENTS.md");
    let agentsContent = await readFile(agentsFile, "utf8");
    await writeFile(agentsFile, agentsContent.replace(/work-state\.json/g, "other-state.json"), "utf8");
    const test4 = await validateDocumentationConformance({ rootDir: tempDir });
    assert.equal(test4.valid, false);
    assert.ok(test4.errors.some((e) => e.includes("DOC_ADAPTER_RESUME_RULE_MISSING")));
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});
