export const EMULATED_SERVICES_ID = "emulated-services";
export const EMULATED_SERVICES_SUPPORTED_VERSION = "0.11.2";

export const EMULATED_SERVICES_PROCESS_LIMITS = Object.freeze({
  maxStdoutBytes: 64 * 1024,
  maxStderrBytes: 64 * 1024,
  maxServices: 32,
  maxTimeoutMs: 120_000,
  terminationGraceMs: 250,
  readinessPollMs: 50,
});

export const EMULATED_SERVICES_ERROR_CODES = Object.freeze({
  CONFIG_INVALID: "E_EMULATED_SERVICES_CONFIG_INVALID",
  UNAVAILABLE: "E_EMULATED_SERVICES_UNAVAILABLE",
  VERSION_UNSUPPORTED: "E_EMULATED_SERVICES_VERSION_UNSUPPORTED",
  OUTPUT_INVALID: "E_EMULATED_SERVICES_OUTPUT_INVALID",
  OUTPUT_LIMIT: "E_EMULATED_SERVICES_OUTPUT_LIMIT",
  TIMEOUT: "E_EMULATED_SERVICES_TIMEOUT",
  CANCELLED: "E_EMULATED_SERVICES_CANCELLED",
  EXECUTION_FAILED: "E_EMULATED_SERVICES_EXECUTION_FAILED",
  ENDPOINT_INVALID: "E_EMULATED_SERVICES_ENDPOINT_INVALID",
  CLEANUP_FAILED: "E_EMULATED_SERVICES_CLEANUP_FAILED",
});
