import { PROVIDER_KINDS, PROVIDER_CAPABILITIES, capabilityFor } from "./capabilities.js";
import {
  E_PROVIDER_INVALID,
  E_PROVIDER_UNAVAILABLE,
  E_PROVIDER_TIMEOUT,
  E_PROVIDER_OUTPUT_INVALID,
  E_PROVIDER_OUTPUT_LIMIT,
  E_PROVIDER_CAPABILITY_UNSUPPORTED,
  E_PROVIDER_AUTHORITY_ESCALATION,
  E_PROVIDER_EXECUTION_FAILED,
  providerError,
} from "./errors.js";
import { createProviderRegistry } from "./registry.js";

export {
  PROVIDER_KINDS,
  PROVIDER_CAPABILITIES,
  capabilityFor,
  E_PROVIDER_INVALID,
  E_PROVIDER_UNAVAILABLE,
  E_PROVIDER_TIMEOUT,
  E_PROVIDER_OUTPUT_INVALID,
  E_PROVIDER_OUTPUT_LIMIT,
  E_PROVIDER_CAPABILITY_UNSUPPORTED,
  E_PROVIDER_AUTHORITY_ESCALATION,
  E_PROVIDER_EXECUTION_FAILED,
  providerError,
  createProviderRegistry,
};
