import {
  E_PERSISTENT_TRANSPORT_FRAME_INVALID,
  E_PERSISTENT_TRANSPORT_FRAME_TOO_LARGE,
  E_PERSISTENT_TRANSPORT_HOST_STALE,
  E_PERSISTENT_TRANSPORT_INVALID_REQUEST,
  E_PERSISTENT_TRANSPORT_INVALID_RESPONSE,
  E_PERSISTENT_TRANSPORT_OWNERSHIP_UNVERIFIED,
  E_PERSISTENT_TRANSPORT_PROTOCOL_MISMATCH,
  E_PERSISTENT_TRANSPORT_START_FAILED,
  E_PERSISTENT_TRANSPORT_TIMEOUT,
  E_PERSISTENT_TRANSPORT_UNAVAILABLE,
} from "../core/error-codes.js";

export const PERSISTENT_TRANSPORT_ERROR_CODES = Object.freeze({
  FRAME_INVALID: E_PERSISTENT_TRANSPORT_FRAME_INVALID,
  FRAME_TOO_LARGE: E_PERSISTENT_TRANSPORT_FRAME_TOO_LARGE,
  HOST_STALE: E_PERSISTENT_TRANSPORT_HOST_STALE,
  INVALID_REQUEST: E_PERSISTENT_TRANSPORT_INVALID_REQUEST,
  INVALID_RESPONSE: E_PERSISTENT_TRANSPORT_INVALID_RESPONSE,
  OWNERSHIP_UNVERIFIED: E_PERSISTENT_TRANSPORT_OWNERSHIP_UNVERIFIED,
  PROTOCOL_MISMATCH: E_PERSISTENT_TRANSPORT_PROTOCOL_MISMATCH,
  START_FAILED: E_PERSISTENT_TRANSPORT_START_FAILED,
  TIMEOUT: E_PERSISTENT_TRANSPORT_TIMEOUT,
  UNAVAILABLE: E_PERSISTENT_TRANSPORT_UNAVAILABLE,
});

export function persistentTransportError(code, message, details = {}) {
  const error = new Error(message);
  error.code = code;
  for (const [key, value] of Object.entries(details)) {
    if (value !== undefined) error[key] = value;
  }
  return error;
}

export function isPersistentTransportError(error) {
  return typeof error?.code === "string" && error.code.startsWith("E_PERSISTENT_TRANSPORT_");
}
