export const REPOSITORY_INDEX_ERROR_CODES = Object.freeze({
  PLATFORM_UNSUPPORTED: "E_REPOSITORY_INDEX_PLATFORM_UNSUPPORTED",
  ENGINE_MISSING: "E_REPOSITORY_INDEX_ENGINE_MISSING",
  ENGINE_DOWNLOAD_FAILED: "E_REPOSITORY_INDEX_ENGINE_DOWNLOAD_FAILED",
  ENGINE_CHECKSUM_MISMATCH: "E_REPOSITORY_INDEX_ENGINE_CHECKSUM_MISMATCH",
  ENGINE_EXTRACTION_FAILED: "E_REPOSITORY_INDEX_ENGINE_EXTRACTION_FAILED",
  ENGINE_VERSION_MISMATCH: "E_REPOSITORY_INDEX_ENGINE_VERSION_MISMATCH",
  ENGINE_EXECUTION_FAILED: "E_REPOSITORY_INDEX_ENGINE_EXECUTION_FAILED",
  ENGINE_OUTPUT_LIMIT: "E_REPOSITORY_INDEX_OUTPUT_LIMIT",
  NOT_INITIALIZED: "E_REPOSITORY_INDEX_NOT_INITIALIZED",
  INDEXING: "E_REPOSITORY_INDEX_INDEXING",
  SERVER_START_FAILED: "E_REPOSITORY_INDEX_SERVER_START_FAILED",
  SERVER_STOP_FAILED: "E_REPOSITORY_INDEX_SERVER_STOP_FAILED",
  SERVER_UNHEALTHY: "E_REPOSITORY_INDEX_SERVER_UNHEALTHY",
  SEARCH_FAILED: "E_REPOSITORY_INDEX_SEARCH_FAILED",
  OUTPUT_INVALID: "E_REPOSITORY_INDEX_OUTPUT_INVALID",
  REBUILD_FAILED: "E_REPOSITORY_INDEX_REBUILD_FAILED",
  REQUEST_INVALID: "E_REPOSITORY_INDEX_REQUEST_INVALID",
  LOCK_UNSAFE: "E_REPOSITORY_INDEX_LOCK_UNSAFE",
});

export function repositoryIndexError(code, message, details = {}) {
  const error = new Error(message);
  error.code = code;
  for (const [key, value] of Object.entries(details)) {
    if (value !== undefined) error[key] = value;
  }
  return error;
}

export function wrapRepositoryIndexError(code, message, cause, details = {}) {
  const error = repositoryIndexError(code, `${message}: ${cause?.message ?? cause}`, {
    ...details,
    cause,
  });
  return error;
}
