export const PROTOCOL_VERSION = 1;

export const FAILURE_CLASSES = Object.freeze([
  "CONTRACT_FAILURE",
  "DISCOVERY_FAILURE",
  "ROUTING_FAILURE",
  "IMPLEMENTATION_FAILURE",
  "VERIFICATION_FAILURE",
  "REGRESSION_FAILURE",
  "REVIEW_FAILURE",
  "CAPABILITY_FAILURE",
  "AUTHORITY_FAILURE",
  "ENVIRONMENT_FAILURE",
  "EXTERNAL_SERVICE_FAILURE",
  "STALE_STATE_FAILURE",
  "OPERATOR_INTERRUPTION",
]);

export const FAILURE_CODES = Object.freeze([
  "E_PREFLIGHT_NOT_READY",
  "E_CONTRACT_MISSING",
  "E_CONTRACT_INVALID",
  "E_CONTRACT_UNRESOLVED_DECISION",
  "E_CONTRACT_STALE",
  "E_ROUTE_MISSING",
  "E_ROUTE_INVALID",
  "E_ROUTE_STALE",
  "E_ROUTE_GUIDE_MISMATCH",
  "E_ROUTE_REASON_MISSING",
  "E_GATE_REQUIRED",
  "E_GATE_UNVERIFIED",
  "E_GATE_STALE",
  "E_GATE_NOT_REQUIRED",
  "E_GATE_INVALID",
  "E_PHASE_FREEZE",
  "E_PHASE_TRANSITION_INVALID",
  "E_PHASE_PREREQUISITE_MISSING",
  "E_PHASE_CHRONOLOGY_INVALID",
  "E_EVIDENCE_REQUIRED",
  "E_EVIDENCE_KIND_INVALID",
  "E_EVIDENCE_STALE",
  "E_EVIDENCE_PARTIAL",
  "E_EVIDENCE_INVALID",
  "E_FUTURE_LIFECYCLE_EVIDENCE",
  "E_CIRCULAR_COMPLETION_REQUIREMENT",
  "E_MIXED_TERMINAL_REQUIREMENT",
  "E_EVIDENCE_COVERAGE_PARTIAL",
  "E_EVIDENCE_COVERAGE_INVALID",
  "E_CHECK_INVALID",
  "E_CHECK_STATUS_CONTRADICTION",
  "E_PROFILE_SOURCE_MISSING",
  "E_PROFILE_SOURCE_UNKNOWN",
  "E_PROFILE_SOURCE_MISCLASSIFIED",
  "E_PROFILE_UNVERIFIED",
  "E_RECEIPT_MISSING",
  "E_RECEIPT_INVALID",
  "E_RECEIPT_TASK_MISMATCH",
  "E_RECEIPT_ROUTE_MISMATCH",
  "E_RECEIPT_STATE_MISMATCH",
  "E_RECEIPT_CONTRACT_MISMATCH",
  "E_RECEIPT_PATH_MISMATCH",
  "E_RECEIPT_CYCLE_MISMATCH",
  "E_COMPLETION_REJECTED",
  "E_COMPLETION_RECOVERY_UNAUTHORIZED",
  "E_COMPLETION_REJECTION_LEDGER_MISMATCH",
  "E_COMPLETION_REJECTION_STATE_FINGERPRINT_MISMATCH",
  "E_COMPLETION_REJECTION_RECEIPT_FINGERPRINT_MISMATCH",
  "E_STATE_MISSING",
  "E_STATE_TASK_MISMATCH",
  "E_STATE_LEDGER_DIVERGENCE",
  "E_PUBLICATION_CLAIM_UNVERIFIED",
  "E_PRODUCTION_READINESS_UNVERIFIED",
  "E_STATE_MISSING_AFTER_PREFLIGHT_READY",
  "E_PREFLIGHT_READY_EVENT_MISSING",
  "E_PREFLIGHT_READY_EVENT_MISMATCH",
  "E_PREFLIGHT_EVENT_MISSING",
  "E_PREFLIGHT_GATE_EVENT_MISSING",
  "E_PREFLIGHT_GATES_STALE",
  "E_TERMINAL_REQUIREMENT_PENDING",
  "E_PUBLICATION_REQUIREMENT_PENDING",
  "E_PRODUCTION_REQUIREMENT_PENDING",
  "E_FUTURE_TERMINAL_EVIDENCE",
  "E_TERMINAL_REQUIREMENT_UNKNOWN",
  "E_TERMINAL_REQUIREMENT_NOT_TERMINAL",
  "E_TERMINAL_REQUIREMENT_TYPE_MISMATCH",
  "E_TERMINAL_STATUS_REGRESSION",
  "E_INSTALLATION_AUTHORITY_REQUIRED",
  "E_AUTHORITY_INVALID",
  "E_AUTHORITY_SCOPE_MISMATCH",
  "E_AUTHORITY_UNTRUSTED_SOURCE",
  "E_VERIFICATION_TOOL_UNAVAILABLE",
  "E_CONTINUITY_INVALID",
  "E_CONTINUITY_SCHEMA_UNSUPPORTED",
  "E_CONTINUITY_STATE_MISSING",
  "E_CONTINUITY_TASK_MISMATCH",
  "E_CONTINUITY_CONTRACT_MISMATCH",
  "E_CONTINUITY_PHASE_MISMATCH",
  "E_CONTINUITY_RECONCILIATION_REQUIRED",
  "E_DIAGNOSIS_REQUIRED",
  "E_DIAGNOSIS_INVALID",
  "E_DIAGNOSIS_EVIDENCE_INVALID",
  "E_DIAGNOSIS_CYCLE_MISMATCH",
  "E_DIAGNOSIS_NO_NEW_INFORMATION",
  "E_PROGRESS_STALLED",
  "E_DIAGNOSTIC_CASE_INVALID",
  "E_DIAGNOSTIC_CASE_CYCLE_MISMATCH",
  "E_DIAGNOSTIC_CASE_EVIDENCE_INVALID",
  "E_OBSERVATION_INVALID",
  "E_CONTRIBUTOR_INVALID",
  "E_CONTRIBUTOR_REFERENCE_INVALID",
  "E_HYPOTHESIS_INVALID",
  "E_HYPOTHESIS_SETTLEMENT_MISSING",
  "E_HYPOTHESIS_DISPOSITION_INVALID",
  "E_HYPOTHESIS_DISPOSITION_EVIDENCE_INVALID",
  "E_INTERVENTION_INVALID",
  "E_INTERVENTION_HYPOTHESIS_MISSING",
  "E_INTERVENTION_REFERENCE_INVALID",
  "E_STRATEGY_OSCILLATION",
  "E_DECISION_CRITERION_INVALID",
  "E_DECISION_NOT_UNRESOLVED",
]);

export const WORK_PHASES = Object.freeze([
  "RECEIVED",
  "DISCOVERING",
  "CONTRACT_READY",
  "ROUTED",
  "DESIGNING",
  "PLANNED",
  "EXECUTING",
  "VERIFYING",
  "DIAGNOSING",
  "CORRECTING",
  "REVIEWING",
  "COMPLETE",
  "BLOCKED",
]);

import { GUIDE_IDS } from "./guide-registry.js";
export { GUIDE_IDS };

export const GUIDE_ORDER = GUIDE_IDS;

export const WORK_TRANSITIONS = Object.freeze({
  RECEIVED: ["DISCOVERING"],
  DISCOVERING: ["CONTRACT_READY"],
  CONTRACT_READY: ["ROUTED"],
  ROUTED: ["DESIGNING", "PLANNED"],
  DESIGNING: ["PLANNED"],
  PLANNED: ["EXECUTING"],
  EXECUTING: ["VERIFYING"],
  VERIFYING: ["DIAGNOSING", "REVIEWING"],
  DIAGNOSING: ["CORRECTING"],
  CORRECTING: ["VERIFYING"],
  REVIEWING: ["COMPLETE", "CORRECTING", "VERIFYING"],
  COMPLETE: [],
  BLOCKED: [],
});

export function isValidTransition(from, to) {
  if (!WORK_PHASES.includes(from) || !WORK_PHASES.includes(to)) return false;
  if (to === "BLOCKED" && from !== "COMPLETE" && from !== "BLOCKED") return true;
  return WORK_TRANSITIONS[from].includes(to);
}

export function assertFailureClass(value) {
  if (!FAILURE_CLASSES.includes(value)) {
    throw new Error(`Unknown failure class: ${value}`);
  }
  return value;
}

export function assertWorkPhase(value) {
  if (!WORK_PHASES.includes(value)) {
    throw new Error(`Unknown work phase: ${value}`);
  }
  return value;
}
