import { DECISION_AUTHORITY, DECISION_EVIDENCE_AUTHORITY, PINNED_JEV_MODEL } from "../decision/constants.js";

export const MODEL_ROUTE_TIERS = Object.freeze(["NONE", "FAST", "STANDARD", "PRIMARY"]);
export const MODEL_ROUTE_POLICY_VERSION = 1;
export const MODEL_ROUTE_PROJECTION_AUTHORITY = DECISION_AUTHORITY;
export const MODEL_ROUTE_PROJECTION_EVIDENCE_AUTHORITY = DECISION_EVIDENCE_AUTHORITY;
export const MODEL_ROUTE_JEV_MODEL = PINNED_JEV_MODEL;

export const MODEL_ROUTE_RANK = Object.freeze({ NONE: 0, FAST: 1, STANDARD: 2, PRIMARY: 3 });

